### ISSUE TITLE
Error while setting up steam_wishlist platform for sensor  // Source: custom_components/steam_wishlist/util.py:25

### ISSUE THREAD

**Issue by Johnyboy1984** [boralyl/steam-wishlist#17]
**Describe the bug**
https://ibb.co/CnpWNBK

**To Reproduce**
----------

**Expected behavior**
---------------------

**Screenshots**
https://ibb.co/CnpWNBK

**Home Assistant Version**:
Home Assistant 2023.5.3

**Custom Component Version**:
SteamWishList: v2.2.4

**Additional context**
--------------------------

**Comment by boralyl** [comment]
Thanks for reporting!  FYI if you click on that button in the upper right i your screenshot it will copy the full error traceback that you can paste in the github issue.

**Comment by boralyl** [comment]
@Johnyboy1984 Thanks again, this should now be fixed in the latest release: https://github.com/boralyl/steam-wishlist/releases/tag/v2.2.5

**Comment by Johnyboy1984** [comment]
Thanks for your quick help. One error no longer occurs, but unfortunately 2 other errors:

1.
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant
Source: custom_components/steam_wishlist/entities.py:118
Integration: Steam Wishlist (documentation)
First occurred: 18:18:56 (1 occurrences)
Last logged: 18:18:56

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 455, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 731, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 845, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 585, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 649, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 591, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/steam_wishlist/entities.py", line 138, in state
    return self.is_on
  File "/config/custom_components/steam_wishlist/entities.py", line 118, in is_on
    return discount_pct > 0
TypeError: '>' not supported between instances of 'NoneType' and 'int'


2.
Logger: homeassistant.components.binary_sensor
Source: custom_components/steam_wishlist/entities.py:118
Integration: Binärsensor (documentation, issues)
First occurred: 18:18:56 (1 occurrences)
Last logged: 18:18:56

Error adding entities for domain binary_sensor with platform steam_wishlist
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 455, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 731, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 845, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 585, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 649, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 591, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/steam_wishlist/entities.py", line 138, in state
    return self.is_on
  File "/config/custom_components/steam_wishlist/entities.py", line 118, in is_on
    return discount_pct > 0
TypeError: '>' not supported between instances of 'NoneType' and 'int'

**Comment by boralyl** [comment]
Thanks, I'll do a more proper fix later today, there appear to be more changes than I expected.

**Comment by boralyl** [comment]
@Johnyboy1984 Try out the latest version and let me know if you encounter any issues or not.  Thanks! https://github.com/boralyl/steam-wishlist/releases/tag/v2.2.6

**Comment by Johnyboy1984** [comment]
@boralyl

Good morning,

I have just imported the latest version into my Home Assistant and since then there have been no more errors. Thank you for your effort. Thank you for your quick and competent response.

**Comment by boralyl** [comment]
Great to hear!  Thank you for confirming!
