### ISSUE TITLE
Integration not working.

### ISSUE THREAD

**Issue by jaydenthorup** [boralyl/steam-wishlist#33]
Added my account fresh, No entities and no sensor. I have 2 log messages as below

Message 1

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:366
integration: Sensor (documentation, issues)
First occurred: 1:07:57 PM (4 occurrences)
Last logged: 1:12:12 PM

Error while setting up steam_wishlist platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/steam_wishlist/sensor.py", line 12, in async_setup_entry
    await hass.data[DOMAIN][config_entry.entry_id].async_register_component(
        "sensor", async_add_entities
    )
  File "/config/custom_components/steam_wishlist/sensor_manager.py", line 153, in async_register_component
    await self.coordinator.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 355, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 478, in _async_refresh
    self.async_update_listeners()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 177, in async_update_listeners
    update_callback()
    ~~~~~~~~~~~~~~~^^
  File "/config/custom_components/steam_wishlist/sensor_manager.py", line 169, in async_update_items
    for game_id, game in self.coordinator.data.items():
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'items'

This error originated from a custom integration.

Logger: custom_components.steam_wishlist.sensor_manager
Source: helpers/update_coordinator.py:392
integration: Steam Wishlist (documentation)
First occurred: 1:07:57 PM (4 occurrences)
Last logged: 1:12:12 PM

Message 2

Error requesting steam_wishlist data: 400, message='Attempt to decode JSON with unexpected mimetype: text/html', url='https://api.steampowered.com/IStoreBrowseService/GetItems/v1?key=3DA57917C41093C752DF629A8B055B64&input_json=%7B%22ids%22:+%5B%7B%22appid%22:+%221300%22%7D,+%7B%22appid%22:+%222210%22%7D,+%7B%22appid%22:+%222360%22%7D,+%7B%22appid%22:+%222390%22%7D,+%7B%22appid%22:+%224500%22%7D,+%7B%22appid%22:+%224920%22%7D,+%7B%22appid%22:+%226980%22%7D,+%7B%22appid%22:+%227940%22%7D,+%7B%22appid%22:+%228980%22%7D,+%7B%22appid%22:+%229060%22%7D,+%7B%22appid%22:+%229200%22%7D,+%7B%22appid%22:+%2210090%22%7D,+%7B%22appid%22:+%2210130%22%7D,+%7B%22appid%22:+%2213210%22%7D,+%7B%22appid%22:+%2213230%22%7D,+%7B%22appid%22:+%2213250%22%7D,+%7B%22appid%22:+%2213600%22%7D,+%7B%22appid%22:+%2217330%22%7D,+%7B%22appid%22:+%2222300%22%7D,+%7B%22appid%22:+%2222340%22%7D,+%7B%22appid%22:+%2222370%22%7D,+%7B%22appid%22:+%2222380%22%7D,+%7B%22appid%22:+%2232460%22%7D,+%7B%22appid%22:+%2233900%22%7D,+%7B%22appid%22:+%2237000%22%7D,+%7B%22appid%22:+%2238430%22%7D,+%7B%22appid%22:+%2239140%22%7D,+%7B%22appid%22:+%2239150%22%7D,+%7B%22appid%22:+%2242670%22%7D,+%7B%22appid%22:+%2242680%22%7D,+%7B%22appid%22:+%2242700%22%7D,+%7B%22appid%22:+%2242718%22%7D,+%7B%22appid%22:+%2249540%22%7D,+%7B%22appid%22:+%2250650%22%7D,+%7B%22appid%22:+%2257900%22%7D,+%7B%22appid%22:+%2265980%22%7D,+%7B%22appid%22:+%2267370%22%7D,+%7B%22appid%22:+%2272850%22%7D,+%7B%22appid%22:+%2298400%22%7D,+%7B%22appid%22:+%2299810%22%7D,+%7B%22appid%22:+%22108600%22%7D,+%7B%22appid%22:+%22115320%22%7D,+%7B%22appid%22:+%22200510%22%7D,+%7B%22appid%22:+%22201810%22%7D,+%7B%22appid%22:+%22202970%22%7D,+%7B%22appid%22:+%22203750%22%7D,+%7B%22appid%22:+%22205100%22%7D,+%7B%22appid%22:+%22207140%22%7D,+%7B%22appid%22:+%22208650%22%7D,+%7B%22appid%22:+%22209160%22%7D,+%7B%22appid%22:+%22209650%22%7D,+%7B%22appid%22:+%22213120%22%7D,+%7B%22appid%22:+%22214490%22%7D,+%7B%22appid%22:+%22214870%22%7D,+%7B%22appid%22:+%22217140%22%7D,+%7B%22appid%22:+%22220200%22%7D,+%7B%22appid%22:+%22220440%22%7D,+%7B%22appid%22:+%22221100%22%7D,+%7B%22appid%22:+%22224060%22%7D,+%7B%22appid%22:+%22224300%22%7D,+%7B%22appid%22:+%22227700%22%7D,+%7B%22appid%22:+%22228360%22%7D,+%7B%22appid%22:+%22231990%22%7D,+%7B%22appid%22:+%22233130%22%7D,+%7B%22appid%22:+%22235460%22%7D,+%7B%22appid%22:+%22236870%22%7D,+%7B%22appid%22:+%22239140%22%7D,+%7B%22appid%22:+%22239160%22%7D,+%7B%22appid%22:+%22241930%22%7D,+%7B%22appid%22:+%22242760%22%7D,+%7B%22appid%22:+%22242860%22%7D,+%7B%22appid%22:+%22243120%22%7D,+%7B%22appid%22:+%22244160%22%7D,+%7B%22appid%22:+%22244430%22%7D,+%7B%22appid%22:+%22245280%22%7D,+%7B%22appid%22:+%22246620%22%7D,+%7B%22appid%22:+%22252490%22%7D,+%7B%22appid%22:+%22252950%22%7D,+%7B%22appid%22:+%22257420%22%7D,+%7B%22appid%22:+%22257510%22%7D,+%7B%22appid%22:+%22258520%22%7D,+%7B%22appid%22:+%22259570%22%7D,+%7B%22appid%22:+%22261530%22%7D,+%7B%22appid%22:+%22261570%22%7D,+%7B%22appid%22:+%22264040%22%7D,+%7B%22appid%22:+%22268130%22%7D,+%7B%22appid%22:+%22268500%22%7D,+%7B%22appid%22:+%22268650%22%7D,+%7B%22appid%22:+%22268910%22%7D,+%7B%22appid%22:+%22273350%22%7D,+%7B%22appid%22:+%22273570%22%7D,+%7B%22appid%22:+%22273580%22%7D,+%7B%22appid%22:+%22273590%22%7D,+%7B%22appid%22:+%22273620%22%7D,+%7B%22appid%22:+%22275850%22%7D,+%7B%22appid%22:+%22281220%22%7D,+%7B%22appid%22:+%22286690%22%7D,+%7B%22appid%22:+%22287390%22%7D,+%7B%22appid%22:+%22287700%22%7D,+%7B%22appid%22:+%22289130%22%7D,+%7B%22appid%22:+%22292030%22%7D,+%7B%22appid%22:+%22294100%22%7D,+%7B%22appid%22:+%22295110%22%7D,+%7B%22appid%22:+%22295790%22%7D,+%7B%22appid%22:+%22298110%22%7D,+%7B%22appid%22:+%22298600%22%7D,+%7B%22appid%22:+%22298900%22%7D,+%7B%22appid%22:+%22299360%22%7D,+%7B%22appid%22:+%22302510%22%7D,+%7B%22appid%22:+%22302670%22%7D,+%7B%22appid%22:+%22303210%22%7D,+%7B%22appid%22:+%22304240%22%7D,+%7B%22appid%22:+%22304430%22%7D,+%7B%22appid%22:+%22305050%22%7D,+%7B%22appid%22:+%22306130%22%7D,+%7B%22appid%22:+%22306760%22%7D,+%7B%22appid%22:+%22310950%22%7D,+%7B%22appid%22:+%22311210%22%7D,+%7B%22appid%22:+%22311340%22%7D,+%7B%22appid%22:+%22312750%22%7D,+%7B%22appid%22:+%22313120%22%7D,+%7B%22appid%22:+%22314150%22%7D,+%7B%22appid%22:+%22314230%22%7D,+%7B%22appid%22:+%22314580%22%7D,+%7B%22appid%22:+%22315440%22%7D,+%7B%22appid%22:+%22316790%22%7D,+%7B%22appid%22:+%22317040%22%7D,+%7B%22appid%22:+%22319510%22%7D,+%7B%22appid%22:+%22319910%22%7D,+%7B%22appid%22:+%22320240%22%7D,+%7B%22appid%22:+%22322500%22%7D,+%7B%22appid%22:+%22324800%22%7D,+%7B%22appid%22:+%22330830%22%7D,+%7B%22appid%22:+%22332800%22%7D,+%7B%22appid%22:+%22333950%22%7D,+%7B%22appid%22:+%22338390%22%7D,+%7B%22appid%22:+%22338930%22%7D,+%7B%22appid%22:+%22340170%22%7D,+%7B%22appid%22:+%22346110%22%7D,+%7B%22appid%22:+%22350280%22%7D,+%7B%22appid%22:+%22352720%22%7D,+%7B%22appid%22:+%22353370%22%7D,+%7B%22appid%22:+%22353380%22%7D,+%7B%22appid%22:+%22354140%22%7D,+%7B%22appid%22:+%22354430%22%7D,+%7B%22appid%22:+%22355250%22%7D,+%7B%22appid%22:+%22355790%22%7D,+%7B%22appid%22:+%22358040%22%7D,+%7B%22appid%22:+%22358180%22%7D,+%7B%22appid%22:+%22358190%22%7D,+%7B%22appid%22:+%22358260%22%7D,+%7B%22appid%22:+%22358280%22%7D,+%7B%22appid%22:+%22358360%22%7D,+%7B%22appid%22:+%22359320%22%7D,+%7B%22appid%22:+%22359550%22%7D,+%7B%22appid%22:+%22359870%22%7D,+%7B%22appid%22:+%22361420%22%7D,+%7B%22appid%22:+%22361690%22%7D,+%7B%22appid%22:+%22362890%22%7D,+%7B%22appid%22:+%22363440%22%7D,+%7B%22appid%22:+%22365590%22%7D,+%7B%22appid%22:+%22367450%22%7D,+%7B%22appid%22:+%22367520%22%7D,+%7B%22appid%22:+%22368070%22%7D,+%7B%22appid%22:+%22368260%22%7D,+%7B%22appid%22:+%22371660%22%7D,+%7B%22appid%22:+%22382900%22%7D,+%7B%22appid%22:+%22383120%22%7D,+%7B%22appid%22:+%22386070%22%7D,+%7B%22appid%22:+%22388090%22%7D,+%7B%22appid%22:+%22388860%22%7D,+%7B%22appid%22:+%22393360%22%7D,+%7B%22appid%22:+%22403640%22%7D,+%7B%22appid%22:+%22410710%22%7D,+%7B%22appid%22:+%22412020%22%7D,+%7B%22appid%22:+%22413360%22%7D,+%7B%22appid%22:+%22419270%22%7D,+%7B%22appid%22:+%22434050%22%7D,+%7B%22appid%22:+%22435150%22%7D,+%7B%22appid%22:+%22445190%22%7D,+%7B%22appid%22:+%22447820%22%7D,+%7B%22appid%22:+%22448850%22%7D,+%7B%22appid%22:+%22450540%22%7D,+%7B%22appid%22:+%22466560%22%7D,+%7B%22appid%22:+%22476600%22%7D,+%7B%22appid%22:+%22482400%22%7D,+%7B%22appid%22:+%22485510%22%7D,+%7B%22appid%22:+%22489830%22%7D,+%7B%22appid%22:+%22498240%22%7D,+%7B%22appid%22:+%22501300%22%7D,+%7B%22appid%22:+%22501590%22%7D,+%7B%22appid%22:+%22504210%22%7D,+%7B%22appid%22:+%22519190%22%7D,+%7B%22appid%22:+%22524220%22%7D,+%7B%22appid%22:+%22526870%22%7D,+%7B%22appid%22:+%22529910%22%7D,+%7B%22appid%22:+%22530620%22%7D,+%7B%22appid%22:+%22532210%22%7D,+%7B%22appid%22:+%22534380%22%7D,+%7B%22appid%22:+%22546560%22%7D,+%7B%22appid%22:+%22548570%22%7D,+%7B%22appid%22:+%22551770%22%7D,+%7B%22appid%22:+%22552500%22%7D,+%7B%22appid%22:+%22553850%22%7D,+%7B%22appid%22:+%22558990%22%7D,+%7B%22appid%22:+%22562860%22%7D,+%7B%22appid%22:+%22570940%22%7D,+%7B%22appid%22:+%22571310%22%7D,+%7B%22appid%22:+%22578080%22%7D,+%7B%22appid%22:+%22578650%22%7D,+%7B%22appid%22:+%22581320%22%7D,+%7B%22appid%22:+%22582160%22%7D,+%7B%22appid%22:+%22587620%22%7D,+%7B%22appid%22:+%22594650%22%7D,+%7B%22appid%22:+%22601150%22%7D,+%7B%22appid%22:+%22601430%22%7D,+%7B%22appid%22:+%22611660%22%7D,+%7B%22appid%22:+%22616560%22%7D,+%7B%22appid%22:+%22620980%22%7D,+%7B%22appid%22:+%22629760%22%7D,+%7B%22appid%22:+%22637650%22%7D,+%7B%22appid%22:+%22644390%22%7D,+%7B%22appid%22:+%22668580%22%7D,+%7B%22appid%22:+%22668840%22%7D,+%7B%22appid%22:+%22692850%22%7D,+%7B%22appid%22:+%22704270%22%7D,+%7B%22appid%22:+%22710920%22%7D,+%7B%22appid%22:+%22739630%22%7D,+%7B%22appid%22:+%22742120%22%7D,+%7B%22appid%22:+%22747660%22%7D,+%7B%22appid%22:+%22753590%22%7D,+%7B%22appid%22:+%22760060%22%7D,+%7B%22appid%22:+%22768520%22%7D,+%7B%22appid%22:+%22798490%22%7D,+%7B%22appid%22:+%22802200%22%7D,+%7B%22appid%22:+%22809140%22%7D,+%7B%22appid%22:+%22812140%22%7D,+%7B%22appid%22:+%22813780%22%7D,+%7B%22appid%22:+%22814380%22%7D,+%7B%22appid%22:+%22823500%22%7D,+%7B%22appid%22:+%22835960%22%7D,+%7B%22appid%22:+%22863550%22%7D,+%7B%22appid%22:+%22870780%22%7D,+%7B%22appid%22:+%22872670%22%7D,+%7B%22appid%22:+%22883710%22%7D,+%7B%22appid%22:+%22889902%22%7D,+%7B%22appid%22:+%22906470%22%7D,+%7B%22appid%22:+%22914620%22%7D,+%7B%22appid%22:+%22920210%22%7D,+%7B%22appid%22:+%22939960%22%7D,+%7B%22appid%22:+%22954740%22%7D,+%7B%22appid%22:+%22955050%22%7D,+%7B%22appid%22:+%22964800%22%7D,+%7B%22appid%22:+%22973810%22%7D,+%7B%22appid%22:+%22979690%22%7D,+%7B%22appid%22:+%22986130%22%7D,+%7B%22appid%22:+%22990080%22%7D,+%7B%22appid%22:+%22996580%22%7D,+%7B%22appid%22:+%22997070%22%7D,+%7B%22appid%22:+%221000410%22%7D,+%7B%22appid%22:+%221017900%22%7D,+%7B%22appid%22:+%221026680%22%7D,+%7B%22appid%22:+%221030840%22%7D,+%7B%22appid%22:+%221034140%22%7D,+%7B%22appid%22:+%221036890%22%7D,+%7B%22appid%22:+%221056960%22%7D,+%7B%22appid%22:+%221056970%22%7D,+%7B%22appid%22:+%221057090%22%7D,+%7B%22appid%22:+%221088850%22%7D,+%7B%22appid%22:+%221091500%22%7D,+%7B%22appid%22:+%221097200%22%7D,+%7B%22appid%22:+%221129540%22%7D,+%7B%22appid%22:+%221135690%22%7D,+%7B%22appid%22:+%221139900%22%7D,+%7B%22appid%22:+%221150440%22%7D,+%7B%22appid%22:+%221151340%22%7D,+%7B%22appid%22:+%221151640%22%7D,+%7B%22appid%22:+%221174180%22%7D,+%7B%22appid%22:+%221190460%22%7D,+%7B%22appid%22:+%221203620%22%7D,+%7B%22appid%22:+%221222140%22%7D,+%7B%22appid%22:+%221222730%22%7D,+%7B%22appid%22:+%221224700%22%7D,+%7B%22appid%22:+%221231990%22%7D,+%7B%22appid%22:+%221237320%22%7D,+%7B%22appid%22:+%221238060%22%7D,+%7B%22appid%22:+%221238820%22%7D,+%7B%22appid%22:+%221250410%22%7D,+%7B%22appid%22:+%221252330%22%7D,+%7B%22appid%22:+%221255560%22%7D,+%7B%22appid%22:+%221259420%22%7D,+%7B%22appid%22:+%221285190%22%7D,+%7B%22appid%22:+%221286830%22%7D,+%7B%22appid%22:+%221314563%22%7D,+%7B%22appid%22:+%221326470%22%7D,+%7B%22appid%22:+%221328670%22%7D,+%7B%22appid%22:+%221332010%22%7D,+%7B%22appid%22:+%221361510%22%7D,+%7B%22appid%22:+%221373510%22%7D,+%7B%22appid%22:+%221373550%22%7D,+%7B%22appid%22:+%221401590%22%7D,+%7B%22appid%22:+%221422440%22%7D,+%7B%22appid%22:+%221449280%22%7D,+%7B%22appid%22:+%221454890%22%7D,+%7B%22appid%22:+%221466860%22%7D,+%7B%22appid%22:+%221496790%22%7D,+%7B%22appid%22:+%221523650%22%7D,+%7B%22appid%22:+%221532690%22%7D,+%7B%22appid%22:+%221533390%22%7D,+%7B%22appid%22:+%221544020%22%7D,+%7B%22appid%22:+%221549970%22%7D,+%7B%22appid%22:+%221550260%22%7D,+%7B%22appid%22:+%221556200%22%7D,+%7B%22appid%22:+%221583230%22%7D,+%7B%22appid%22:+%221593500%22%7D,+%7B%22appid%22:+%221611910%22%7D,+%7B%22appid%22:+%221627720%22%7D,+%7B%22appid%22:+%221659040%22%7D,+%7B%22appid%22:+%221659420%22%7D,+%7B%22appid%22:+%221674170%22%7D,+%7B%22appid%22:+%221675200%22%7D,+%7B%22appid%22:+%221708091%22%7D,+%7B%22appid%22:+%221716740%22%7D,+%7B%22appid%22:+%221766740%22%7D,+%7B%22appid%22:+%221789480%22%7D,+%7B%22appid%22:+%221794680%22%7D,+%7B%22appid%22:+%221817070%22%7D,+%7B%22appid%22:+%221817190%22%7D,+%7B%22appid%22:+%221850570%22%7D,+%7B%22appid%22:+%221938090%22%7D,+%7B%22appid%22:+%221944430%22%7D,+%7B%22appid%22:+%221966720%22%7D,+%7B%22appid%22:+%221989270%22%7D,+%7B%22appid%22:+%222013360%22%7D,+%7B%22appid%22:+%222073850%22%7D,+%7B%22appid%22:+%222080690%22%7D,+%7B%22appid%22:+%222208920%22%7D,+%7B%22appid%22:+%222221920%22%7D,+%7B%22appid%22:+%222420110%22%7D,+%7B%22appid%22:+%222497920%22%7D,+%7B%22appid%22:+%222519060%22%7D,+%7B%22appid%22:+%222587620%22%7D,+%7B%22appid%22:+%222694420%22%7D,+%7B%22appid%22:+%222881650%22%7D,+%7B%22appid%22:+%222933130%22%7D,+%7B%22appid%22:+%223017860%22%7D%5D,+%22context%22:+%7B%22language%22:+%22en%22,+%22country_code%22:+%22US%22%7D,+%22data_request%22:+%7B%22include_assets%22:+true,+%22include_reviews%22:+true,+%22include_basic_info%22:+true%7D%7D'

**Comment by boralyl** [comment]
Thanks for reporting! My hunch is it's requesting details for too many games at once. Could you share your steamid for debugging purposes? Thanks!

**Comment by boralyl** [comment]
@jaydenthorup I believe this issue is now fixed in https://github.com/boralyl/steam-wishlist/releases/tag/v3.0.2 Let me know if that's not the case.
